---
# Case config
# case_name: "{{ lookup('env', 'CASE_NAME') }}"
# case_bundle_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}"
# case_archive_dir: "{{ case_bundle_dir }}/archive"
# case_inventory_name: "{{ lookup('env', 'CASE_INV_NAME') }}"

# case_target_namespace: "{{ lookup('env', 'CASE_TARGET_NAMESPACE') }}"

registry_private_host: "{{ lookup('env', 'REGISTRY_PRIVATE_HOST') }}"
registry_private_port: "{{ lookup('env', 'REGISTRY_PRIVATE_PORT') }}"
registry_private_url: "{{ registry_private_host }}:{{ registry_private_port }}"
