---
# Target Registry
# -----------------------------------------------------------------------------
registry_public_host: "{{ lookup('env', 'REGISTRY_PUBLIC_HOST') }}"
registry_public_port: "{{ lookup('env', 'REGISTRY_PUBLIC_PORT') }}"
registry_public_url: "{{ registry_public_host }}:{{ registry_public_port }}"

# Extras config
# -----------------------------------------------------------------------------
extras_name: "{{ lookup('env', 'EXTRAS_NAME') }}"
extras_version: "{{ lookup('env', 'EXTRAS_VERSION') }}"


# Configure working directory
# -----------------------------------------------------------------------------
mirror_working_dir: "{{ lookup('env', 'MIRROR_WORKING_DIR') }}"
