---
- hosts: localhost
  vars:
    case_name: ibm-cp-common-services
    case_namespace: ibm-common-services
    case_source: https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-cp-common-services/1.9.0/ibm-cp-common-services-1.9.0.tgz?raw=true
    case_bundle_dir: /tmp/casebundle-common-services
    exclude_images:
      - ibm-auditlogging
      - ibm-cpp
      - ibm-cs-commonui
      - ibm-cs-healthcheck
      - ibm-cs-iam
      - ibm-cs-mongodb
      - ibm-cs-monitoring
      - ibm-events-operator
      - ibm-management-ingress
      - ibm-platform-api-operator
      - ibm-zen
    case_inventory_name: "ibmCommonServiceOperatorSetup"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_airgap.case_prepare
    - ibm.mas_airgap.case_config_icsp
