---
- hosts: localhost
  any_errors_fatal: true

# 1. Deploy & configure the cluster
# -----------------------------------------------------------------------------
- name: Deploy QuickBurn cluster in Fyre
  import_playbook: ocp/provision-quickburn.yml

# # 2. Install MongoDb
# # -----------------------------------------------------------------------------
#- name: Install MongoDb (Community Edition)
#  import_playbook: dependencies/install-mongodb-ce.yml
#  vars:
#    mongodb_storage_class: ocs-storagecluster-ceph-rbd
#    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# 6. Install & configure MAS
# -----------------------------------------------------------------------------
- name: Install & configure MAS
  import_playbook: mas/install-suite.yml
  vars:
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
    airgap_install: true

# 3. Install SLS
# -----------------------------------------------------------------------------
- name: Install SLS
  import_playbook: sls/install-sls.yml
  vars:
    sls_storage_class: ocs-storagecluster-ceph-rbd
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
    # Default to re-using the MAS entitlement key if we do not provide a specific one for SLS
    sls_entitlement_username: "{{ lookup('env', 'SLS_ENTITLEMENT_USERNAME') | default('cp', true) }}"
    sls_entitlement_key: "{{ lookup('env', 'SLS_ENTITLEMENT_KEY') | default(lookup('env', 'IBM_ENTITLEMENT_KEY'), true) }}"

    # Use the generated mongodb configuration
    mongodb_namespace: "{{ lookup('env', 'MONGODB_NAMESPACE') | default('mongoce', True) }}"
    mongodb_cfg_file: "{{ mas_config_dir }}/mongo-{{ mongodb_namespace }}.yml"

    # Bootstrap from the mas_config_dir
    bootstrap:
      license_id: "{{ lookup('env', 'SLS_LICENSE_ID') | default('', true) }}"
      registration_key: "{{ lookup('env', 'SLS_REGISTRATION_KEY') | default('', true) }}"
      entitlement_file: "{{mas_config_dir}}/entitlement.lic"
