---
- hosts: localhost
  vars:
    case_name: "ibm-truststore-mgr"
    case_source: "https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-truststore-mgr/1.2.2/ibm-sls-1.2.2.tgz?raw=true"
    case_bundle_dir: /tmp/casebundle-truststore-mgr
    exclude_images: []
    case_inventory_name: "ibmTrustStoreMgrSetup"
    registry_public_host: "{{ lookup('env', 'REGISTRY_PUBLIC_HOST') }}"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_airgap.case_prepare
    - ibm.mas_airgap.case_mirror
