---
- hosts: localhost
  vars:
    case_name: "ibm-sls"
    case_source: "https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-sls/3.3.1/ibm-sls-3.3.1.tgz?raw=true"
    case_bundle_dir: /tmp/casebundle-sls
    exclude_images: []
    case_inventory_name: "ibmSlsSetup"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_airgap.case_prepare
    - ibm.mas_airgap.case_mirror
