---
- hosts: localhost
  vars:
    case_name: ibm-uds
    case_source: https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-uds/2.0.7/ibm-uds-2.0.7.tgz?raw=true
    case_bundle_dir: /tmp/casebundle-uds
    exclude_images: []
    case_inventory_name: "operatorSetup"

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_airgap.case_prepare
    - ibm.mas_airgap.case_mirror
