---
# Mirrors the following content which is REQUIRED to add Maximo Predict to an existing
# Maximo Application Suite Core Services installation:
# 1. IBM Maximo Optimizer
#
# This playbook aligns with the ibm.mas_devops.oneclick_add_predict playbook

- hosts: localhost
  any_errors_fatal: true

  vars:
    catalog_tag: "{{ lookup('env', 'MAS_CATALOG_VERSION') | default ('v8-220927-amd64', True) }}"
    mirror_mode: "{{ lookup('env', 'MIRROR_MODE') | default ('direct', True) }}"

    mirror_mas_predict: "{{ lookup('env', 'MIRROR_MAS_PREDICT') | default ('True', True) | bool }}"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"
    - name: Load CASE bundle versions
      include_vars:
        file: "{{ playbook_dir }}/../common_vars/casebundles/{{ catalog_tag }}.yml"

  roles:
    # 1. IBM Maximo Predict
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.mirror_case_prepare
      when:
        - mirror_mas_predict
        - mirror_mode != "from-filesystem"
      vars:
        case_name: ibm-mas-predict
        case_version: "{{ mas_predict_version }}"
        exclude_images: []

    - name: ibm.mas_airgap.mirror_images
      when: mirror_mas_predict
      vars:
        manifest_name: ibm-mas-predict
        manifest_version: "{{ mas_predict_version }}"
