---
# Mirrors the following content which is REQUIRED to install Maximo Application Suite Core Services:
# 1. IBM Maximo Operator Catalog
# 2. MongoDb Community Edition
# 3. IBM Cloud Pak Foundation Services
# 4. IBM User Data Services
# 5. IBM Suite License Service
# 6. IBM Truststore Manager
# 7. IBM Maximo Application Suite Core

- hosts: localhost
  any_errors_fatal: true
  vars:
    catalog_tag: "20220727"
    catalog_digest: sha256:d0c3c21b8c93fbccbe0ccde7ffbe401db46d30c68329c0ad5f3e95659520608d

    mirror_catalog: "{{ lookup('env', 'MIRROR_CATALOG') | default ('False', True) | bool }}"
    mirror_mongoce: "{{ lookup('env', 'MIRROR_MONGOCE') | default ('False', True) | bool }}"
    mirror_common_svcs: "{{ lookup('env', 'MIRROR_COMMON_SVCS') | default ('False', True) | bool }}"
    mirror_tsm: "{{ lookup('env', 'MIRROR_TSM') | default ('False', True) | bool }}"
    mirror_mas_core: "{{ lookup('env', 'MIRROR_MAS_CORE') | default ('False', True) | bool }}"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
        fail_msg: "One or more required environment variables are not defined"
    - name: Load CASE bundle versions
      include_vars:
        file: "common_vars/casebundles/ibm-maximo-operator-catalog-{{ catalog_tag }}.yml"

  roles:
    # 1. IBM Maximo Operator Catalog
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.mirror_images
      when: mirror_catalog
      vars:
        images_to_mirror:
          - name: cpopen/ibm-mas-operator-catalog
            registry: icr.io
            tag: "{{ catalog_tag }}"
            digest: "{{ catalog_digest }}"


    # 2. MongoDb Community Edition
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.mirror_images
      when: mirror_mongoce
      vars:
        images_to_mirror:
          - name: mongodb/mongodb-kubernetes-operator
            registry: quay.io
            tag: 0.7.0
            digest: sha256:e19ae43539521f0350fb71684757dc535fc989deb75f3789cd84b782489eda80

          - name: mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook
            registry: quay.io
            tag: 1.0.2
            digest: sha256:da347eb74525715a670280545e78ecee1195ec2630037b3821591c87f7a314ee

          - name: mongodb/mongodb-agent
            registry: quay.io
            tag: 11.0.5.6963-1
            digest: sha256:4db6e9c7df3d9421dcc09e98c5b43ba9d95952eae3c2ccbfdb83a49743b3195f

          - name: mongodb/mongodb-kubernetes-readinessprobe
            registry: quay.io
            tag: 1.0.4
            digest: sha256:bf5a4ffc8d2d257d6d9eb45d3e521f30b2e049a9b60ddc8e4865448e035502ca

          - name: ibmmas/mongo
            registry: quay.io
            tag: 4.2.6
            digest: sha256:8c48baa1571469d7f5ae6d603b92b8027ada5eb39826c009cb33a13b46864908


    # 3. IBM Cloud Pak Foundation Services
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_common_svcs
      vars:
        case_name: ibm-cp-common-services
        case_version: "{{ common_svcs_version }}"
        exclude_images:
          - ibm-auditlogging
          - ibm-cpp
          - ibm-cs-commonui
          - ibm-cs-healthcheck
          - ibm-cs-iam
          - ibm-cs-mongodb
          - ibm-cs-monitoring
          - ibm-events-operator
          - ibm-management-ingress
          - ibm-platform-api-operator
          - ibm-zen

    - name: ibm.mas_airgap.case_mirror
      when: mirror_common_svcs
      vars:
        case_name: ibm-cp-common-services
        case_version: "{{ common_svcs_version }}"
        case_inventory_name: "ibmCommonServiceOperatorSetup"


    # 4. IBM User Data Services
    # -------------------------------------------------------------------------


    # 5. IBM Suite License Service
    # -------------------------------------------------------------------------


    # 6. IBM Truststore Manager
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_tsm
      vars:
        case_name: ibm-truststore-mgr
        case_version: "{{ tsm_version }}"

    - name: ibm.mas_airgap.case_mirror
      when: mirror_tsm
      vars:
        case_name: ibm-truststore-mgr
        case_version: "{{ tsm_version }}"
        case_inventory_name: "ibmTrustStoreMgrSetup"


    # 7. IBM Maximo Application Suite Core
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_mas_core
      vars:
        case_name: ibm-mas
        case_version: "{{ mas_core_version }}"
        exclude_images:
          - ibm-mas-assist
          - ibm-mas-hputilities
          - ibm-mas-iot
          - ibm-mas-manage
          - ibm-mas-monitor
          - ibm-mas-predict
          - ibm-mas-safety
          - ibm-mas-visualinspection
          - ibm-mas-mso
          - ibm-mas-optimizer
          - ibm-sls

    - name: ibm.mas_airgap.case_mirror
      when: mirror_mas_core
      vars:
        case_name: ibm-mas
        case_version: "{{ mas_core_version }}"
        case_inventory_name: "ibmMasSetup"
