---
# Mirrors the following content which is REQUIRED to add Maximo Assist to an existing
# Maximo Application Suite Core Services installation:
# 1. CP4D
# 2. IBM Zen Services
# 3. Watson Discovery
# 4. IBM Maximo Assist
#
# This playbook aligns with the ibm.mas_devops.oneclick_add_assist playbook

- hosts: localhost
  any_errors_fatal: true

  vars:
    catalog_tag: "{{ lookup('env', 'MAS_CATALOG_VERSION') | default ('v8-220805-amd64', True) }}"

    mirror_cp4d: "{{ lookup('env', 'MIRROR_CP4D') | default ('True', True) | bool }}"
    mirror_mas_assist: "{{ lookup('env', 'MIRROR_MAS_ASSIST') | default ('True', True) | bool }}"
    mirror_wd: "{{ lookup('env', 'MIRROR_WD') | default ('True', True) | bool }}"
    mirror_zen: "{{ lookup('env', 'MIRROR_ZEN') | default ('True', True) | bool }}"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"
    - name: Load CASE bundle versions
      include_vars:
        file: "{{ playbook_dir }}/../common_vars/casebundles/{{ catalog_tag }}.yml"

  roles:
    # 1. CP4D
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_cp4d
      vars:
        case_name: ibm-cp-datacore
        case_version: "{{ cp4d_version }}"
        exclude_images:
          - ibm-analyticsengine
          - ibm-bigsql-case
          - ibm-ccs
          - ibm-cde
          - ibm-cpd-scheduling
          - ibm-datagate-prod
          - ibm-datarefinery
          - ibm-db2aaservice
          - ibm-db2uoperator
          - ibm-db2wh
          - ibm-dmc
          - ibm-dods
          - ibm-dp
          - ibm-dv-case
          - ibm-hadoop
          - ibm-iis
          - ibm-mdm
          - ibm-rstudio
          - ibm-spss
          - ibm-watson-openscale
          - ibm-wkc
          - ibm-wml-accelerator
          - ibm-wml-cpd
          - ibm-wsl
          - ibm-zen

    - name: ibm.mas_airgap.case_mirror
      when: mirror_cp4d
      vars:
        case_name: ibm-cp-datacore
        case_version: "{{ cp4d_version }}"
        case_inventory_name: "cpdPlatformOperator"

    # 2. IBM Zen
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_zen
      vars:
        case_name: ibm-zen
        case_version: "{{ zen_version }}"
        exclude_images: []

    - name: ibm.mas_airgap.case_mirror
      when: mirror_zen
      vars:
        case_name: ibm-zen
        case_version: "{{ zen_version }}"
        case_inventory_name: "zen_deploy"

    # 3. Watson Discovery
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_wd
      vars:
        case_name: ibm-watson-discovery
        case_version: "{{ wd_version }}"
        exclude_images: []

    - name: ibm.mas_airgap.case_mirror
      when: mirror_wd
      vars:
        case_name: ibm-watson-discovery
        case_version: "{{ wd_version }}"
        case_inventory_name: "discoveryOperators"

    # 4. IBM Maximo Assist
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_mas_assist
      vars:
        case_name: ibm-mas-assist
        case_version: "{{ mas_assist_version }}"
        exclude_images: []

    - name: ibm.mas_airgap.case_mirror
      when: mirror_mas_assist
      vars:
        case_name: ibm-mas-assist
        case_version: "{{ mas_assist_version }}"
        case_inventory_name: "ibmMasAssistSetup"
