---
# Mirrors the following content which is REQUIRED to add Maximo Safety to an existing
# Maximo Application Suite Core Services with Maximo IoT installation:
# 1. IBM Maximo Safety
#
# This playbook aligns with the ibm.mas_devops.oneclick_add_safety playbook

- hosts: localhost
  any_errors_fatal: true

  vars:
    catalog_tag: "{{ lookup('env', 'MAS_CATALOG_VERSION') | default ('v8-220805-amd64', True) }}"

    mirror_mas_safety: "{{ lookup('env', 'MIRROR_MAS_SAFETY') | default ('True', True) | bool }}"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
          - lookup('env', 'IBM_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"
    - name: Load CASE bundle versions
      include_vars:
        file: "{{ playbook_dir }}/../common_vars/casebundles/{{ catalog_tag }}.yml"

  roles:
    # 1. IBM Maximo Safety
    # -------------------------------------------------------------------------
    - name: ibm.mas_airgap.case_prepare
      when: mirror_mas_safety
      vars:
        case_name: ibm-mas-safety
        case_version: "{{ mas_safety_version }}"
        exclude_images: []

    - name: ibm.mas_airgap.case_mirror
      when: mirror_mas_safety
      vars:
        case_name: ibm-mas-safety
        case_version: "{{ mas_safety_version }}"
        case_inventory_name: "ibmMasSafetySetup"
