---
# Approximate runtime: 30 minutes (on a good connection)
- hosts: localhost
  vars:
    case_name: "ibm-mas"
    case_source: "https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-mas/8.7.2/ibm-mas-8.7.2.tgz?raw=true"
    case_bundle_dir: /tmp/casebundle-mas
    exclude_images:
      - ibm-mas-assist
      - ibm-mas-hputilities
      - ibm-mas-iot
      - ibm-mas-manage
      - ibm-mas-monitor
      - ibm-mas-predict
      - ibm-mas-safety
      - ibm-mas-visualinspection
      - ibm-mas-mso
      - ibm-sls
    case_inventory_name: "ibmMasSetup"

  pre_tasks:
    # Note that REGISTRY_USERNAME and REGISTRY_PASSWORD are not required.
    # They are only needed if you have set up authentication on your private registry
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'REGISTRY_PUBLIC_HOST') != ""
          - lookup('env', 'REGISTRY_PUBLIC_PORT') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_airgap.case_prepare
    - ibm.mas_airgap.case_mirror
