---


# 1. Update default cluster image pull secret
# =============================================================================

# 1.1 Generate the new secret content
- name: "update-pull-secret : Set new secret content"
  vars:
    registryAuthB64: "{{ registry_auth | b64encode }}"
    content:
      - "{\"auths\":{\"{{ registry_private_url }}\":{\"username\":\"{{ registry_username }}\",\"password\":\"{{ registry_password }}\",\"email\":\"{{ registry_username }}\",\"auth\":\"{{ registryAuthB64 }}\"}"
      - "}"
      - "}"
  set_fact:
    new_secret: "{{ content | join('') }}"

# 1.4. Overwrite the secret
- name: "update-pull-secret : Update new pull-secret"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: pull-secret
        namespace: openshift-config
      data:
        .dockerconfigjson: "{{ new_secret | to_json | b64encode }}"
  register: secretUpdateResult

- name: "update-pull-secret : Debug change state"
  debug:
    msg: "Default Pull Secret Changed ....... {{ secretUpdateResult.changed }}"
