---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-registry
  name: docker-registry
  namespace: "{{ registry_namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: docker.io/library/registry:2.6.2
        volumeMounts:
        - name: repo-vol
          mountPath: "/var/lib/registry"
        - name: certs-vol
          mountPath: "/certs"
          readOnly: true
        - name: auth-vol
          mountPath: "/auth"
          readOnly: true
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "RegistryRealm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
      imagePullSecrets:
        - name: docker-io-entitlement
      volumes:
      - name: repo-vol
        persistentVolumeClaim:
          claimName: docker-repo2-pvc
      - name: certs-vol
        secret:
          secretName: mas-docker-registry-secret
      - name: auth-vol
        secret:
          secretName: mas-docker-registry-auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: "{{ registry_namespace }}"
spec:
  selector:
    app: docker-registry
  ports:
  - port: 5000
    targetPort: 5000
