---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-repo2-pvc
  namespace: "{{ registry_namespace }}"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ registry_size }}
  storageClassName: {{ registry_storage_class }}
