kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: docker-registry-route
  namespace: "{{ registry_namespace }}"
spec:
  host: "docker-registry.{{ cluster_url }}"
  to:
    kind: Service
    name: docker-registry
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
