# mkdocs serve

site_name: MAS Airgap Collection
site_url: https://ibm-mas.github.io/ansible-airgap

repo_name: GitHub
repo_url: https://github.com/ibm-mas/ansible-airgap
edit_uri: blob/master/docs/

nav:
  - 'Home': index.md
  - 'Full Stack Playbooks':
    - 'IBM Cloud': playbooks/fullstack-quickburn.md
  - 'Lite Playbooks':
    - 'Core only on QuickBurn': playbooks/lite-core-quickburn.md
  - 'Other Playbooks':
    - 'CASE Bundle Playbooks': playbooks/case.md
    - 'FVT Environment Playbook': playbooks/fvt.md
    - 'MAS Playbook': playbooks/mas.md
    - 'OCP Playbook': playbooks/ocp.md
    - 'SLS Playbook': playbooks/sls.md
  - 'Roles':
    - 'case_install': roles/case_install.md
    - 'case_mirror': roles/case_mirror.md
    - 'case_prepare': roles/case_prepare.md
    - 'fvt_simulate_airgap': roles/fvt_simulate_airgap.md
    - 'ocp_mirror_mas_deps': roles/ocp_mirror_mas_deps.md

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
  # Add this to support expandable sections
  #- pymdownx.details

# https://squidfunk.github.io/mkdocs-material/extensions/admonition/
# Note
# Abstract
# Info
# Tip
# Success
# Question
# Warning
# Failure
# Danger
# Bug
# Example
# Quote
