---
# Get Registry facts from environment variables if they have not been passed to the role
registry_private_host: "{{ lookup('env', 'REGISTRY_PRIVATE_HOST') }}"
registry_private_port: "{{ lookup('env', 'REGISTRY_PRIVATE_PORT') }}"
registry_private_url: "{{ registry_private_host }}:{{ registry_private_port }}"

registry_private_ca_file: "{{ lookup('env', 'REGISTRY_PRIVATE_CA_FILE') }}"

registry_auth_username: "{{ lookup('env', 'REGISTRY_AUTH_USERNAME') }}"
registry_auth_password: "{{ lookup('env', 'REGISTRY_AUTH_PASSWORD') }}"
registry_auth: "{{ registry_auth_username }}:{{ registry_auth_password }}"
