galaxy_info:
  author: Paul Stone
  description: Modify OCP cluster configuration to simulate an airgap type environment
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies: []
