---
# Ideally we would add quay.io here as well, but we can't until we mirror all the images used by OCP itself
airgap_network_exclusions: "icr.io cp.icr.io wiotp-docker-local.artifactory.swg-devops.com"

registry_private_ca_file: "{{ lookup('env', 'REGISTRY_PRIVATE_CA_FILE') }}"
registry_private_ca_crt: "{{ lookup('file', registry_private_ca_file) }}"
