---
# Ideally we would add quay.io here as well, but we can't until we mirror all the images used by OCP itself
# removed artifactory from blocked list while fixing tecton cert issue
# airgap_network_exclusions: "icr.io cp.icr.io wiotp-docker-local.artifactory.swg-devops.com"
airgap_network_exclusions: "icr.io cp.icr.io"
