---
- hosts: localhost
  vars:
    # General configuration
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    cluster_type: quickburn
    username: "{{ lookup('env', 'FYRE_USERNAME') }}"
    password: "{{ lookup('env', 'FYRE_APIKEY') }}"
    # Case config
    case_name: "{{ lookup('env', 'CASE_NAME') }}"
    case_bundle_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}"
    case_archive_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}/archive"
    case_inventory_name: "{{ lookup('env', 'CASE_INV_NAME') }}"
    # Airgap control parameters:
    debugs: "_oc_status,installOperatorResult"

  roles:
    - ibm.mas_airgap.case_install
