---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if required properties are not provided"
  assert:
    that:
      - case_name is defined and case_name != ""
      - case_bundle_dir is defined and case_bundle_dir != ""
      - case_inventory_name is defined and case_inventory_name != ""
      - registry_public_host is defined and registry_public_host != ""
      - ibm_entitlement_key is defined and ibm_entitlement_key != ""
    fail_msg: "One or more required properties are missing"


# 2. Check for required software
# -----------------------------------------------------------------------------
- name: "Test if cloudctl is installed"
  shell: cloudctl version
  register: _cloudctl_version
  ignore_errors: true

- name: "Fail if cloudctl is not installed"
  assert:
    that: ( _cloudctl_version['rc'] == 0 )
    fail_msg: "cloudctl tool must be installed."


# 3. Debug
# -----------------------------------------------------------------------------
- name: "Airgap setup configuration"
  debug:
    msg:
      - "Case Name .............................. {{ case_name }}"
      - "Case Bundle Directory .................. {{ case_bundle_dir }}"
      - "Inventory Name ......................... {{ case_inventory_name }}"
      - "Registry Public Host ................... {{ registry_public_host }}"


# 3. Set up Authentication for ICR
# -----------------------------------------------------------------------------
# TODO: For now this is limited to unauthenticed registry (like the one set up by the "registry" role)

- name: "Setup ICR Registry Credentials"
  shell: >
    cloudctl case launch --action configureCredsAirgap \
      --case {{ case_bundle_dir }}/case/{{ case_name }} \
      --inventory {{ case_inventory_name }} \
      --tolerance 1 \
      --args "--registry cp.icr.io --user cp --pass {{ ibm_entitlement_key }}"
  register: configureCredsResult


# 4. Perform a Dry Run
# -----------------------------------------------------------------------------
# Perform a dry run first, if it fails it will report why and nothing will be changed om the target system
- name: "Mirror Images Dry Run ({{ case_bundle_dir }}/case/{{ case_name }})"
  shell: >
    cloudctl case launch --action mirror-images \
      --case {{ case_bundle_dir }}/case/{{ case_name }} \
      --inventory {{ case_inventory_name }} \
      --tolerance 1 \
      --args "--registry {{ registry_public_host }} --inputDir {{ case_archive_dir }} --skipDelta true --dryRun true" \
    | tee {{ case_bundle_dir }}/mirror-{{ case_name }}-{{ case_inventory_name }}-dryrun.log
  register: dryrun_result
  # if USE_SKOPEO flag is set, the command doesn't perform a dry run
  when: lookup('env', 'USE_SKOPEO') != 'True'

- name: "Debug Dry Run"
  debug:
    msg: "{{ dryrun_result.stdout_lines }}"


# 5. Execute the Mirror
# -----------------------------------------------------------------------------
- name: Mirror Images
  when: not mirror_dry_run_only
  shell: >
    cloudctl case launch --action mirror-images \
      --case {{ case_bundle_dir }}/case/{{ case_name }} \
      --inventory {{ case_inventory_name }} \
      --tolerance 1 \
      --args "--registry {{ registry_public_host }} --inputDir {{ case_archive_dir }} --skipDelta true" \
    | tee {{ case_bundle_dir }}/mirror-{{ case_name }}-{{ case_inventory_name }}.log
  register: mirror_result
  # This can intermittently fail with "504 Gateway Time-out" errors, retry until sucessful.
  until: mirror_result['rc'] == 0 or mirror_result['stdout'] is not search('504 Gateway Time', multiline=True)
  retries: 10

- name: "Debug Mirror"
  when: not mirror_dry_run_only
  debug:
    msg: "{{ mirror_result.stdout_lines }}"
