---
# we use the oc login token as our cluster internal registry password.
- name: get oc token
  shell: >
    oc whoami -t
  register: ocUserToken

- name: Set oc token
  set_fact:
    ocToken: "{{ ocUserToken.stdout }}"

# we need to configure credentials for the internal registry using both the
# external and internal hostnames.
- name: Configure repository credentials for target cluster repo
  shell: >
    cloudctl case launch --action configureCredsAirgap \
      --case {{ case_bundle_dir }}/case/{{ case_name }} \
      --inventory {{ case_inventory_name }} \
      --tolerance 1 \
      --args "--registry {{ item }} \
        --user {{ registryUsername }} \
        --pass {{ registryPassword }}"
  register: configureCredsResult
  loop:
  - "{{ registryPublicHost }}"
  - "{{ registryFromCluster }}"
