# While using the OpenShift Internal Registry, we need to change references to cp.icr.io,cp/ to be cp.icr.io/cp.
# Remove this when we use a different Image Registry

- name: Get CASE archive image csvs
  find:
    paths: "{{ case_archive_dir }}"
    patterns: "*-images.csv"
  register: _image_csvs

- name: Replace multilevel image references
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: '^cp.icr.io,cp/'
    replace: 'cp.icr.io/cp,'
  loop: "{{_image_csvs.files}}"
  register: _replace_results

# OpenShift Internal Registry needs us to have projects (namespaces) created to hold the mirrored images
- name: Calculate Required Namespaces
  shell: |
    sed -e 's/.*,\(.*\)\/.*/\1/' {{ case_archive_dir }}/*-images.csv | grep -v digest_source | sort -u
  register: regnamespaces

- name: Create Registry Image Namespaces
  vars:
    namespace: "{{item}}"
  community.kubernetes.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/namespace.yaml') }}"
  loop: "{{ regnamespaces.stdout_lines }}"
