---
# Copy template/override files to allow airgap install of devepment build

- name: Copy development files into case
  copy:
    src: "{{ dev_overrides }}/"
    dest: "{{ case_bundle_dir }}"
  when:
    - dev_overrides is defined
    - not dev_overrides == ""
