---
# don't copy images from these apps
excludeImages: "ibm-mas-assist,ibm-mas-hputilities,ibm-mas-iot,ibm-mas-manage,ibm-mas-monitor,ibm-mas-predict,ibm-mas-safety,ibm-mas-visualinspection,ibm-sls"

# Case config
case_name: "{{ lookup('env', 'CASE_NAME') }}"
case_source: "{{ lookup('env', 'CASE_SOURCE') }}"
case_bundle_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}"
case_archive_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}/archive"
case_inventory_name: "{{ lookup('env', 'CASE_INV_NAME') }}"
