---
# Target Registry
# -----------------------------------------------------------------------------
registry_public_host: "{{ lookup('env', 'REGISTRY_PUBLIC_HOST') }}"
registry_public_port: "{{ lookup('env', 'REGISTRY_PUBLIC_PORT') }}"
registry_public_url: "{{ registry_public_host }}:{{ registry_public_port }}"

# Working directories
# -----------------------------------------------------------------------------
case_work_dir: "{{ lookup('env', 'CASE_WORK_DIR') | default( ansible_env.HOME ~ '/mas_airgap', True) }}"
case_bundle_dir: "{{ case_work_dir }}/{{ case_name }}"
case_archive_dir: "{{ case_bundle_dir }}/archive"

# Case config
# -----------------------------------------------------------------------------
case_name: "{{ lookup('env', 'CASE_NAME') }}"
case_inventory_name: "{{ lookup('env', 'CASE_INV_NAME') }}"

# Authentication - IBM
# -----------------------------------------------------------------------------
ibm_entitlement_key: "{{ lookup('env', 'IBM_ENTITLEMENT_KEY') }}"
ibm_auth: "cp:{{ ibm_entitlement_key }}"

# Authentication - RedHat
# -----------------------------------------------------------------------------
redhat_connect_username: "{{ lookup('env', 'REDHAT_CONNECT_USERNAME') }}"
redhat_connect_password: "{{ lookup('env', 'REDHAT_CONNECT_PASSWORD') }}"
redhat_connect_auth: "{{ redhat_connect_username }}:{{ redhat_connect_password }}"

# Authentication - Target Registry
# -----------------------------------------------------------------------------
registry_username: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
registry_password: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"
registry_auth: "{{ registry_username }}:{{ registry_password }}"

# Workarounds for known issues
# -----------------------------------------------------------------------------
# These images are not mirrored when we run the main CASE mirror for the db2u operator
# If we change the version of db2u CASE we will need to update these values
db2u_extra_images:
  - name: db2u.auxiliary.auth
    digest: sha256:e87775abfd0364c9695314e59a4cf735d587d4a755c53a1298f116660f093164
  - name: db2u.instdb
    digest: sha256:95860f732d03a347c49bfdb5df52df14454bec26ad35f17292e4f353550095f7
  - name: etcd
    digest: sha256:876ff0a27eecfae4a1d4f1f8b4da977ab09c36c8deeb64c0317c2fc162a16957
  - name: db2u.tools
    digest: sha256:c7662c7d63f4e1b9166e27ba60878bd7d8027ac42fc4cbec2dea3d54cb82abc8
  - name: db2u
    digest: sha256:493aba982bfc721f15b89b75900fdd699275b0a72c380bcf9b694be5ee107a6c
