---
# Get Registry facts from environment variables if they have not been passed to the role
registry_public_host: "{{ lookup('env', 'REGISTRY_PUBLIC_HOST') }}"
registry_public_port: "{{ lookup('env', 'REGISTRY_PUBLIC_PORT') }}"
registry_public_url: "{{ registry_public_host }}:{{ registry_public_port }}"

# Case config
case_name: "{{ lookup('env', 'CASE_NAME') }}"
case_bundle_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}"
case_archive_dir: "{{ case_bundle_dir }}/archive"
case_inventory_name: "{{ lookup('env', 'CASE_INV_NAME') }}"

ibm_entitlement_key: "{{ lookup('env', 'IBM_ENTITLEMENT_KEY') }}"
ibm_auth: "cp:{{ ibm_entitlement_key }}"

redhat_connect_username: "{{ lookup('env', 'REDHAT_CONNECT_USERNAME') }}"
redhat_connect_password: "{{ lookup('env', 'REDHAT_CONNECT_PASSWORD') }}"
redhat_connect_auth: "{{ redhat_connect_username }}:{{ redhat_connect_password }}"

registry_auth_username: "{{ lookup('env', 'REGISTRY_AUTH_USERNAME') }}"
registry_auth_password: "{{ lookup('env', 'REGISTRY_AUTH_PASSWORD') }}"
registry_auth: "{{ registry_auth_username }}:{{ registry_auth_password }}"
