---
# What cluster types does this role support
supported_cluster_types:
  - quickburn
# don't copy images from these apps
excludeImages: "ibm-mas-assist,ibm-mas-hputilities,ibm-mas-iot,ibm-mas-manage,ibm-mas-monitor,ibm-mas-predict,ibm-mas-safety,ibm-mas-visualinspection,ibm-sls"

# Get Registry facts from environment variables if they have not been passed to the role
registryPublicHost: "{{ lookup('env', 'REGISTRY_PUBLIC_HOST') }}"
registryFromCluster: "{{ lookup('env', 'REGISTRY_FROM_CLUSTER') }}"
registryUsername: "{{ lookup('env', 'REGISTRY_USERNAME') }}"
registryPassword: "{{ lookup('env', 'REGISTRY_PASSWORD') }}"

# Case config
case_name: "{{ lookup('env', 'CASE_NAME') }}"
case_bundle_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}"
case_archive_dir: "{{ lookup('env', 'CASE_BUNDLE_DIR') }}/archive"
case_inventory_name: "{{ lookup('env', 'CASE_INV_NAME') }}"
