---
# 0.1 mirror images to airgap registry
- name: "Mirror Case Prereq Images"
  include_role:
    name: ibm.mas_devops.airgap_mirror_case
  vars:
    case_name: "{{ this_case.name }}"
    case_bundle_dir: "{{ role_path }}/../ocp_mirror_mas_deps/files/case-bundles/{{ this_case.name }}"
    case_archive_dir: "{{ role_path }}/../ocp_mirror_mas_deps/files/case-bundles/{{ this_case.name }}/archive"
    case_inventory_name: " {{ this_case.inv }} "
    target_namespace: "mas-{{ lookup('env', 'MAS_INSTANCE_ID') }}-core"
    ignoreMirrorError: false
    cp_icr_entitlement: abc
    registries: "{{ this_case.registries }}"
  loop: "{{ mirror_images.case_bundles }}"
  loop_control:
    loop_var: this_case
