---
# Configure the OpenShift Internal Registry so it can be used to mirror container image
# --------------------------------------------------------------------------------------

# Set the default route on the internal registry
- name: Patch registry default route to expose the internal registry
  community.kubernetes.k8s:
    definition:
      apiVersion: imageregistry.operator.openshift.io/v1
      kind: Config
      metadata:
        name: cluster
      spec:
        defaultRoute: true

- name: Wait for the default route
  community.kubernetes.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: "default-route"
    namespace: openshift-image-registry
    wait: yes
    wait_sleep: 10
    wait_timeout: 60 # 1 min until we give up waiting for the CRD to get into the expected state
  register: defaultRoute

# Get the address of the internal registry
- name: Set Registry Name
  set_fact:
    registryPublicHost: "{{ defaultRoute.resources[0].spec.host }}"
    registryFromCluster: "image-registry.openshift-image-registry.svc:5000"

- name: "Default Route"
  debug:
    msg:
      - "Public Registry Host ....... {{ registryPublicHost }}"
      - "Registry Host From Cluster . {{ registryFromCluster }}"
  when: debugs is search ('registryHosts')

# we use the oc login token as our cluster internal registry password.
- name: get oc token
  shell: >
    oc whoami -t
  register: ocUserToken

- name: Set registry credentials
  set_fact:
    registryUsername: "kubeadmin"
    registryPassword: "{{ ocUserToken.stdout }}"
