---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if type is not provided"
  when: cluster_type is not defined or cluster_type == ""
  fail:
    msg: "cluster_type property is required"

- name: "Fail if cluster_type is not supported"
  when: cluster_type is not in supported_cluster_types
  fail:
    msg: "cluster_type '{{ cluster_type }}' property is not supported by this role"

- name: "Fail if cluster_name is not provided"
  when: cluster_name is not defined or cluster_name == ""
  fail:
    msg: "cluster_name property is required"

- name: "Simulated Airgap setup configuration"
  debug:
    msg:
      - "Cluster Name . {{ cluster_name }}"
      - "Cluster Type . {{ cluster_type }}"

# 2. Check cluster login
# -----------------------------------------------------------------------------
- name: "Check cluster login"
  shell: oc status
  register: _oc_status
  ignore_errors: true

- debug:
    msg:
      - "OC Status: {{ _oc_status }}"

- name: "Login to cluster"
  include_role:
    name: ibm.mas_devops.ocp_login
  vars:
    login_server: "https://api.{{ cluster_name }}.cp.fyre.ibm.com:6443"
  when: ( _oc_status['rc'] != 0 ) or (not _oc_status['stdout'] is search ( login_server ) )

# 3. Set up the OpenShift internal registry
# --------------------------------
- include_tasks: "tasks/configure-internal-registry.yml"
  when:
    - use_internal_registry is defined
    - use_internal_registry

# 4. Set up the OpenShift docker registry
# --------------------------------
- include_tasks: "tasks/configure-docker-registry.yml"
  when:
    - use_docker_registry is defined
    - use_docker_registry

# 6. Configure the cluster network to simulate airgap installations
# -----------------------------------------------------------------------------
- include_tasks: "tasks/configure-network.yml"
  when:
    - configure_network is defined
    - configure_network
