namespace: ibm
name: mas_airgap
version: 3.0.0
readme: README.md
authors:
  - Paul Stone <stonepd@uk.ibm.com>
  - David Parker <parkerda@uk.ibm.com>
description: MAS Air Gap Install Ansible Collection
license:
  - EPL-2.0
tags:
  - ibm
  - mas
  - rhocp
dependencies:
  "ibm.mas_devops": ">=11.0.0,<12.0.0"
repository: https://github.com/ibm-mas/ansible-airgap/
documentation: https://ibm-mas.github.io/ansible-airgap/
homepage: https://ibm-mas.github.io/ansible-airgap/
issues: https://github.com/ibm-mas/ansible-airgap/issues
build_ignore: []
