namespace: ibm
name: mas_airgap
version: 2.0.0
readme: README.md
authors:
  - Paul Stone <stonepd@uk.ibm.com>
  - David Parker <parkerda@uk.ibm.com>
description: MAS Air Gap Install Ansible Collection
license:
  - EPL-2.0
tags:
  - ibm
  - mas
  - rhocp
dependencies:
  "kubernetes.core": ">=2.2.0,<3.0.0"
  "ibm.mas_devops": ">=10.0.0,<11.0.0"
repository: https://github.com/ibm-mas/ansible-airgap/
documentation: https://ibm-mas.github.io/ansible-airgap/
homepage: https://ibm-mas.github.io/ansible-airgap/
issues: https://github.com/ibm-mas/ansible-airgap/issues
build_ignore: []
