---
# 1. Fail if required parameters are not set
# -----------------------------------------------------------------------------
- name: "Fail if digest_image_map_namespace has not been provided"
  assert:
    that:
      - digest_image_map_namespace is defined and digest_image_map_namespace != ""
      - case_name is defined and case_name != ""
      - case_version is defined and case_version != ""
    fail_msg: "Required properties have not been set"


# 2. Setup Working directories
# -----------------------------------------------------------------------------
- name: "Initialize facts (1/2)"
  set_fact:
    digest_image_map_name: "{{ case_name }}-image-map"
    digest_image_map_file: "{{ role_path }}/../../common_vars/digests/{{ case_name }}/{{ case_version }}.yaml"

# Manage operator v8.4.0 references the wrong config map name
- name: "Workaround for bug in ibm-mas-manage v8.4.0"
  when:
    - case_name == "ibm-mas-manage"
    - case_version == "8.4.0"
  set_fact:
    digest_image_map_name: "ibm-manage-image-map"

# Optimizer operator v8.2.0 also references the wrong config map name
- name: "Workaround for bug in ibm-mas-optimizer v8.2.0"
  when:
    - case_name == "ibm-mas-optimizer"
    - case_version == "8.2.0"
  set_fact:
    digest_image_map_name: "ibm-optimizer-image-map"

- name: "Debug Image Digest Config Map"
  debug:
    msg:
      - "Namespace .......................... {{ digest_image_map_namespace }}"
      - "Case Name .......................... {{ case_name }}"
      - "Case Version ....................... {{ case_version }}"
      - "Digest Map Name .................... {{ digest_image_map_name }}"
      - "Digest Map Local File .............. {{ digest_image_map_file }}"


# 3. Install the Digest Image Map
# -----------------------------------------------------------------------------
- name: "Initialize facts (2/2)"
  set_fact:
    digest_image_map_data: "{{ lookup('file', digest_image_map_file) }}"

- name: "Install digest config maps"
  kubernetes.core.k8s:
    template: 'templates/configmap.yml.j2'
