---
# 1. Fail if required parameters are not set
# -----------------------------------------------------------------------------
- name: "Fail if digest_image_map_namespace has not been provided"
  assert:
    that:
      - digest_image_map_namespace is defined and digest_image_map_namespace != ""
      - case_name is defined and case_name != ""
      - case_version is defined and case_version != ""
    fail_msg: "Required properties have not been set"


# 2. Setup Working directories
# -----------------------------------------------------------------------------
- name: "Initialize facts (1/3)"
  set_fact:
    case_bundle_dir: "{{ case_work_dir }}/{{ case_name }}/{{ case_version }}"

- name: "Initialize facts (2/3)"
  set_fact:
    case_archive_dir: "{{ case_bundle_dir }}/archive"
    digest_image_map_name: "{{ case_name }}-image-map"
    digest_image_map_file: "{{ case_bundle_dir }}/case/{{ case_name }}/inventory/{{ inventory_names[case_name] }}/files/image-map.yaml"

- name: "Debug Image Digest Config Map"
  debug:
    msg:
      - "Namespace .......................... {{ digest_image_map_namespace }}"
      - "Case Name .......................... {{ case_name }}"
      - "Case Version ....................... {{ case_version }}"
      - "Digest Map Name .................... {{ digest_image_map_name }}"
      - "Digest Map Local File .............. {{ digest_image_map_file }}"


# 3. Prepare the case bundle
# -----------------------------------------------------------------------------
- name: "Prepare the case"
  include_role:
    name: ibm.mas_airgap.case_prepare


# 4. Install the Digest Image Map
# -----------------------------------------------------------------------------
- name: "Initialize facts (3/3)"
  set_fact:
    digest_image_map_data: "{{ lookup('file', digest_image_map_file) }}"

- name: "Install digest config maps"
  kubernetes.core.k8s:
    template: 'templates/configmap.yml.j2'
