---

# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if required properties are not provided"
  assert:
    that:
      - openshift_operators_version is defined and openshift_operators_version != ""
      - log_dir is defined and log_dir != ""
      - registry_public_host is defined and registry_public_host != ""
      - redhat_connect_username is defined and redhat_connect_username != ""
      - redhat_connect_password is defined and redhat_connect_password != ""
    fail_msg: "One or more required properties are missing"


# 2. Check for required software
# -----------------------------------------------------------------------------
- name: "Test if oc is installed"
  shell: oc help
  register: _oc_help
  ignore_errors: true

- name: "Fail if oc is not installed"
  assert:
    that: ( _oc_help['rc'] == 0 )
    fail_msg: "oc tool must be installed."


# 3. Debug
# -----------------------------------------------------------------------------
- name: "Airgap setup configuration"
  debug:
    msg:
      - "OpenShift Operators Version ............ {{ openshift_operators_version }}"
      - "Log Directory .......................... {{ log_dir }}"
      - "Registry Public Host ................... {{ registry_public_host }}"
      - "Registry Public Port ................... {{ registry_public_port }}"
      - "registry_username ...................... {{ registry_username }}"
      - "registry_password ...................... {{ registry_password }}"
      - "redhat_connect_username ................ {{ redhat_connect_username }}"
      - "redhat_connect_password ................ {{ redhat_connect_password }}"
      - "registry_name1: {{ registry_public_url }}"
      - "registry_auth1: {{ registry_auth }}"
      - "registry_name2: registry.connect.redhat.com"
      - "registry_auth2: {{ redhat_connect_auth }}"
      - "registry_name3: registry.redhat.io"
      - "registry_auth3: {{ redhat_connect_auth }}"

# 4. Set up authentication for the mirroring process
# -----------------------------------------------------------------------------

# 4.1 Prepare the directory
- name: Creates airgap auth directory
  file:
    path: "{{ ansible_env.HOME }}/.airgap/auth"
    state: directory

# 4.2 Private registry
- name: Create auth file for private registry
  vars:
    registry_name1: "{{ registry_public_url }}"
    registry_auth1: "{{ registry_auth }}"
    registry_name2: registry.connect.redhat.com
    registry_auth2: "{{ redhat_connect_auth }}"
    registry_name3: registry.redhat.io
    registry_auth3: "{{ redhat_connect_auth }}"
  ansible.builtin.template:
    src: templates/auth-file.json.j2
    dest: "{{ ansible_env.HOME }}/.airgap/auth/auth.json"


# 5.  Mirror RedHat Operator Images
# -----------------------------------------------------------------------------
- name: Mirror RedHat Operator Images (This may take several minutes)
  shell: >
    oc adm catalog mirror -a {{ ansible_env.HOME }}/.airgap/auth/auth.json registry.redhat.io/redhat/redhat-operator-index:v{{ openshift_operators_version }} {{ registry_public_host }}:{{ registry_public_port }}/redhat --insecure=true \
    | tee {{ log_dir }}/catalog-mirror-redhat-{{ openshift_operators_version }}.log
  register: mirror_result

- name: "Debug Mirror"
  debug:
    msg: "{{ mirror_result.stdout_lines }}"


# 6.Mirror Community Operator Images
# -----------------------------------------------------------------------------
- name: Mirror Community Operator Images (This may take several minutes)
  shell: >
    oc adm catalog mirror -a {{ ansible_env.HOME }}/.airgap/auth/auth.json registry.redhat.io/redhat/community-operator-index:v{{ openshift_operators_version }} {{ registry_public_host }}:{{ registry_public_port }}/redhat --insecure=true \
    | tee {{ log_dir }}/catalog-mirror-community-{{ openshift_operators_version }}.log
  register: mirror_result

- name: "Debug Mirror"
  debug:
    msg: "{{ mirror_result.stdout_lines }}"

# 7. Mirror Certified Operator Images
# -----------------------------------------------------------------------------
- name: Mirror Certified Operator Images (This may take several minutes)
  shell: >
    oc adm catalog mirror -a {{ ansible_env.HOME }}/.airgap/auth/auth.json registry.redhat.io/redhat/certified-operator-index:v{{ openshift_operators_version }} {{ registry_public_host }}:{{ registry_public_port }}/redhat --insecure=true \
    | tee {{ log_dir }}/catalog-mirror-certified-{{ openshift_operators_version }}.log
  register: mirror_result

- name: "Debug Mirror"
  debug:
    msg: "{{ mirror_result.stdout_lines }}"

# 8. Mirror RedHat Marketplace Images
# -----------------------------------------------------------------------------
- name: Mirror RedHat Marketplace Images (This may take several minutes)
  shell: >
    oc adm catalog mirror -a {{ ansible_env.HOME }}/.airgap/auth/auth.json registry.redhat.io/redhat/redhat-marketplace-index:v{{ openshift_operators_version }} {{ registry_public_host }}:{{ registry_public_port }}/redhat --insecure=true \
    | tee {{ log_dir }}/catalog-mirror-marketplace-{{ openshift_operators_version }}.log
  register: mirror_result

- name: "Debug Mirror"
  debug:
    msg: "{{ mirror_result.stdout_lines }}"
