---
- hosts: localhost
  vars:
    # General configuration
    cluster_name: "{{ lookup('env', 'CLUSTER_NAME') }}"
    cluster_url: "apps.{{ cluster_name }}.cp.fyre.ibm.com"
    cluster_type: quickburn
    username: "{{ lookup('env', 'FYRE_USERNAME') }}"
    password: "{{ lookup('env', 'FYRE_APIKEY') }}"
    ocp_version: "{{ lookup('env', 'OCP_VERSION') }}"
    # Fyre specific configuration
    fyre_cluster_size: "{{ lookup('env', 'FYRE_CLUSTER_SIZE') | default('large', true) }}"
    fyre_product_id: "{{ lookup('env', 'FYRE_PRODUCT_ID') }}"
    # Airgap flag
    airgap_install: true

    # --- Dev catalog settings ----------------------------------------------------------------------------------------
    # Only required when using the development catalog sources for pre-release installation
    # These are used to set up image pull secret in the openshift-marketplace namespace
    artifactory_username: "{{ lookup('env', 'W3_USERNAME') | lower }}"
    artifactory_apikey: "{{ lookup('env', 'ARTIFACTORY_APIKEY') }}"
    # -----------------------------------------------------------------------------------------------------------------

    # optionally you can provide information to setup github oauth in the cluster
    # oauth:
    #   github_client_secret_value: "{{ lookup('env', 'OAUTH_CLIENT_SECRET') }}"
    #   github_client_id_value: "{{ lookup('env', 'OAUTH_CLIENT_ID') }}"
    #   github_hostname: github.ibm.com
    #   groups:
    #     - name: group1
    #       users:
    #         - user1
    #         - user2
    #       groups_cluster_rolebindings:
    #         - cluster-admin
    #   organizations:
    #     - org1
    #     - org2
    debugs: "registryHosts,mirrorImageResult,configureClusterResult"
    use_internal_registry: false
    use_docker_registry: true

    # Case config for the MAS case bundle
    case_name: "ibm-mas"
    case_inventory_name: "ibmMasSetup"
    case_bundle_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}"
    case_archive_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}/archive"
    #case_source: "https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-mas/8.5.0/ibm-mas-8.5.0.tgz?raw=true"


# 2. Prepare IBM MAS CASE Bundle, download if necessary
- name: Prepare CASE
  import_playbook: ../case/prepare-case.yml
  vars:
    excludeImages: "ibm-mas-manage,ibm-mas-assist,ibm-mas-hputilities,ibm-mas-iot,ibm-mas-monitor,ibm-mas-predict,ibm-mas-safety,ibm-mas-visualinspection,ibm-sls"
    case_name: "ibm-mas"
    case_inventory_name: "ibmMasSetup"
    case_bundle_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}"
    case_archive_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}/archive"

# 3. Configure the airgap registry, cluster and mirror images
- name: Mirror Images
  import_playbook: ../case/mirror-case.yml
  vars:
    use_internal_registry: false
    case_name: "ibm-mas"
    case_inventory_name: "ibmMasSetup"
    case_bundle_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}"
    case_archive_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}/archive"

# 4. Perform the Operator Install defined in the CASE bundle.
#    Note that this may or may not fully install the operator, depending on the CASE.
- name: CASE Install Operator
  import_playbook: ../case/install-case.yml
  vars:
    case_name: "ibm-mas"
    case_inventory_name: "ibmMasSetup"
    case_bundle_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}"
    case_archive_dir: "{{ lookup('env', 'MAS_CASE_BUNDLE_DIR') }}/archive"
    target_namespace: "mas-{{ lookup('env', 'MAS_INSTANCE_ID') }}-core"

# 5. Install & configure MAS
# -----------------------------------------------------------------------------
- name: Install & configure MAS
  import_playbook: ../../../../ibm/mas_devops/playbooks/mas/install-suite.yml
  vars:
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
    airgap_install: true
