galaxy_info:
  author: Paul Stone (@stonepd)
  description: Mirror images required to run the
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp

dependencies:
  #- role: ibm.mas_devops.ocp_login
