---
# Disable network access to public image repositories
# -----------------------------------------------------------------------------

# The hosts file needs to include a line for the registry service, otherwise the
# file will get out of sync with the version on the file system, and MCO updates will fail.
- name: Lookup Registry Service
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: image-registry
    namespace: openshift-image-registry
  register: registry_service_result

- debug:
    var: registry_service_result

# Disable Network access to public repositories
## Set the /etc/hosts file on each cluster node to mis-direct any calls to icr.io, cp.icr.io and wiotp-docker-local.artifactory.swg-devops.com
- name: Create hosts file
  vars:
    hosts_file_content: |
      127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      1.2.3.4     {{ airgap_network_exclusions }}
      {{ registry_service_result.resources[0].spec.clusterIP }} image-registry.openshift-image-registry.svc image-registry.openshift-image-registry.svc.cluster.local # openshift-generated-node-resolver
    hosts_file_b64: "{{ hosts_file_content | b64encode }} "
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/mc.yml.j2'
  register: result

- debug:
    var: result

# Wait until the nodes have applied the updates
- name: Wait for Machine Configs to update
  when: result.changed
  include_tasks: "tasks/wait-machine-config-update.yml"
