---

# 1. Install the catalog source
# -----------------------------------------------------------------------------
- name: Install catalog source
  shell: >
    cloudctl case launch --action install-catalog \
      --case {{ case_bundle_dir }}/case/{{ case_name }} \
      --inventory {{ case_inventory_name }} \
      --namespace {{ case_target_namespace }} \
      --tolerance 1 \
      --args "--inputDir {{ case_archive_dir }} --registry {{ registry_private_host }}"
  register: install_catalog_result

- name: Debug catalog installation
  debug:
    msg: "{{ install_catalog_result.stdout_lines }}"


# 2. Wait for the catalog source to be ready
# -----------------------------------------------------------------------------
- name: Wait for the catalog source to be ready
  community.kubernetes.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: CatalogSource
    name: "{{ case_name }}-operator-catalog" # This is the naming convention but may vary
    namespace: openshift-marketplace
    wait: yes
    wait_sleep: 10
    wait_timeout: 60 # 1 min until we give up waiting for the CRD to get into the expected state
    #wait_condition:
    #  type: Admitted
    #  status: True
  register: catalogSource
