---
# Configure the Cluster to pull images from the mirror
# - Configure the Image Content Source Policy
# - wait for nodes to restart


# 1. Param check
# -----------------------------------------------------------------------------
- name: "Check for required parameters"
  assert:
    that:
      - registry_private_host is defined and registry_private_host != ""
      - registry_private_port is defined and registry_private_port != ""
      - registry_private_ca_file is defined and registry_private_ca_file != ""


# 2. Configure CA trust
# -----------------------------------------------------------------------------
- name: Set up trust for the registry
  include_tasks: "tasks/trust.yml"


# 3. Create ImageContentSourcePolicy for MAS & dependencies
# -----------------------------------------------------------------------------
- name: Create configmap
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/imagecontentsourcepolicy.yml.j2'


# 4. Wait until the nodes have applied the updates
# -----------------------------------------------------------------------------
- name: Wait for Machine Configs to update
  include_tasks: "tasks/wait-machine-config-update.yml"
