---

# 1. Read the CA cert from the file
# -----------------------------------------------------------------------------
- name: Read the CA cert
  set_fact:
    registry_private_ca_crt: "{{ lookup('file', registry_private_ca_file) }}"


# 2. Create configmap containing the CA cert of our airgap registry
# -----------------------------------------------------------------------------
- name: Create configmap
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/configmap.yml.j2'


# 3. Patch cluster config to use this configmap in spec.additionalTrustedCA
# -----------------------------------------------------------------------------
- name: Patch cluster image configuration
  kubernetes.core.k8s:
    api_version: config.openshift.io/v1
    kind: Image
    name: cluster
    apply: yes
    definition:
      spec:
        additionalTrustedCA:
          name: registry-config


# 4. Patch the cluster so it can pull from private registry
# -----------------------------------------------------------------------------
#- name: Patch cluster trusted CA
#  kubernetes.core.k8s:
#    api_version: config.openshift.io/v1
#    kind: proxy
#    name: cluster
#    apply: yes
#    definition:
#      spec:
#        trustedCA:
#          name: registry-config


# 4. Add registry ca crt to RHCOS trust bundle
# -----------------------------------------------------------------------------
- name: MachineConfig for registry-ca.crt
  vars:
    registry_ca_crt_b64: "{{ registry_private_ca_crt | b64encode }}"
  kubernetes.core.k8s:
    apply: yes
    template: 'templates/mc.yml.j2'
  register: result


# 4. Add registry ca crt to RHCOS trust bundle
# -----------------------------------------------------------------------------
- debug:
    var: result


# 4. Add registry ca crt to RHCOS trust bundle
# -----------------------------------------------------------------------------
# Wait until the nodes have applied the updates
- name: Wait for Machine Configs to update
  when: result.changed
  include_tasks: "{{ role_path }}/../../common_tasks/wait-machine-config-update.yml"


