---


# 1. Update default cluster image pull secret
# =============================================================================

# 1.1 Generate the new secret content
- name: "update-pull-secret : Set new secret content"
  vars:
    registryAuthB64: "{{ registry_auth | b64encode }}"
    content:
      - "{\"auths\":{\"{{ registry_private_url }}\":{\"username\":\"{{ registry_auth_username }}\",\"password\":\"{{ registry_auth_password }}\",\"email\":\"{{ registry_auth_username }}\",\"auth\":\"{{ registryAuthB64 }}\"}"
      - "}"
      - "}"
  set_fact:
    new_secret: "{{ content | join('') }}"

# 1.2 Find the existing secret, and we are going to modify it rather than replace
- name: "update-pull-secret : Retrieve existing pull-secret content"
  kubernetes.core.k8s_info:
    api: v1
    kind: Secret
    name: pull-secret
    namespace: openshift-config
  register: pullsecret

- name: "update-pull-secret : Get the original cred secrets"
  set_fact:
    original_secret: "{{ item.data }}"
  with_items: "{{ pullsecret.resources }}"
  no_log: true

- name: "update-pull-secret : Get the dockerconfigjson info"
  set_fact:
    secret_string: '{{ original_secret[".dockerconfigjson"] | b64decode | from_json }}'

# 1.3 Append our new credentials to the secret
- name: "update-pull-secret : Combine new secret content"
  set_fact:
    new_secret_string: '{{ secret_string | combine( new_secret, recursive=True) }}'

# 1.4. Overwrite the secret
- name: "update-pull-secret : Update new pull-secret"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: pull-secret
        namespace: openshift-config
      data:
        .dockerconfigjson: "{{ new_secret_string | to_json | b64encode }}"
  register: secretUpdateResult

- name: "update-pull-secret : Debug change state"
  debug:
    msg: "Default Pull Secret Changed ....... {{ secretUpdateResult.changed }}"
