name: Publish Ansible Collection
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
jobs:
  ansible-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Initialise the build system
        run: |
          chmod u+x $GITHUB_WORKSPACE/build/bin/*.sh
          $GITHUB_WORKSPACE/build/bin/initbuild.sh
          source $GITHUB_WORKSPACE/build/bin/.functions.sh
          python -m pip install -q ansible==2.10.3 yamllint

      # Note: Use "--format standard" to ensure filenames and line numbers are in the output
      # https://gitanswer.com/yamllint-missing-filenames-and-line-numbers-in-github-action-output-python-794550803
      - name: Validate that the ansible collection lints successfully
        run: |
          yamllint --format standard -c $GITHUB_WORKSPACE/yamllint.yaml $GITHUB_WORKSPACE/ibm/mas_airgap

      - name: Build the Ansible collection
        run: |
          $GITHUB_WORKSPACE/build/bin/build-collection.sh

      - name: Upload Ansible Collection
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/ibm/mas_airgap/ibm-mas_airgap-${{ env.VERSION }}.tar.gz
          asset_name: ibm-mas_airgap-${{ env.VERSION }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

      # Publish
      - name: Publish Collection
        run: |
          ansible-galaxy collection publish ${{ github.workspace }}/ibm/mas_airgap/ibm-mas_airgap-${{ env.VERSION }}.tar.gz --token=${{ secrets.ANSIBLE_GALAXY_TOKEN }}
