name: Build Ansible Collection
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        # Without this option, we don't get the tag information
        with:
          fetch-depth: 0

      - name: Initialise the build system
        run: |
          chmod u+x $GITHUB_WORKSPACE/build/bin/*.sh
          $GITHUB_WORKSPACE/build/bin/initbuild.sh
          source $GITHUB_WORKSPACE/build/bin/.functions.sh
          python -m pip install -q ansible==2.10.3 yamllint

      # Note: Use "--format standard" to ensure filenames and line numbers are in the output
      # https://gitanswer.com/yamllint-missing-filenames-and-line-numbers-in-github-action-output-python-794550803
      - name: Validate that the ansible collection lints successfully
        run: |
          yamllint --format standard -c $GITHUB_WORKSPACE/yamllint.yaml $GITHUB_WORKSPACE/ibm/mas_airgap

      - name: Build the Ansible collection
        run: |
          $GITHUB_WORKSPACE/build/bin/build-collection.sh

      - name: Upload Ansible Collection
        uses: actions/upload-artifact@v2
        with:
          name: ibm-mas_airgap-${{ env.VERSION }}.tar.gz
          path: ${{ github.workspace }}/ibm/mas_airgap/ibm-mas_airgap-${{ env.VERSION }}.tar.gz
          retention-days: 30

      - name: Perform dependency check
        uses: dependency-check/Dependency-Check_Action@main
        id: owasp-depcheck
        with:
          project: 'ansible-airgap'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload dependency check results
        uses: actions/upload-artifact@v2
        with:
           name: OWASP dependency check report
           path: ${{github.workspace}}/reports
           retention-days: 30
